### ISSUE TITLE
MoBIE

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-playground-display#1]
@NicoKiaru Should we move the `MobieBdvSupplier` class from this repository into the MoBIE repo?

**Comment by tischi** [comment]
@NicoKiaru 

In general, would you prefer if I moved everything that is currently only used by `MoBIE` to the mobie repo? That would also include the `AccumulateMixedProjector` and so on; I have the feeling this would be cleaner.

In this case I would not even need the bdv-playground-display repo until I am also using your layering and alpha logic.

**Comment by NicoKiaru** [comment]
Yes, you can do it, there you have more freedom to do some modifications,

**Comment by tischi** [comment]
OK! 

1. Should I then delete "my classes" from this repo?
2. I don't think I need a zoom for now, because we found some other way of covering our use-case. Once that's implemented I could show you and we can think about how to maybe integrate this into this repo.

**Comment by NicoKiaru** [comment]
Ok, no problem. If you use a different package you can just 'add' your classes. We'll delete them later.

**Comment by tischi** [comment]
I tried, but now I am getting this error:

```
xception in thread "main" com.google.gson.JsonParseException: cannot serialize de.embl.cba.mobie.bdv.MobieBdvSupplier; did you forget to register a subtype?
	at sc.fiji.persist.RuntimeTypeAdapterFactory$1.write(RuntimeTypeAdapterFactory.java:275)
	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:191)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:638)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.setDefaultBdvSupplier(SourceAndConverterBdvDisplayService.java:130)
```

Do you have any idea?

**Comment by NicoKiaru** [comment]
Did you write this class as well ? 

https://github.com/NicoKiaru/bigdataviewer-playground-display/blob/master/src/main/java/sc/fiji/bdvpg/bdv/supplier/mobie/MobieBdvSupplierAdapter.java

Your supplier needs to be serializable, using a gson adapter

**Comment by tischi** [comment]
Yes, I did! Do I need to register it somewhere or should it find it automatically?

**Comment by tischi** [comment]
Works now. The adapter was referring  to the wrong class.

Now I get:

```
Exception in thread "main" java.lang.IllegalArgumentException: types and labels must be unique
	at sc.fiji.persist.RuntimeTypeAdapterFactory.registerSubtype(RuntimeTypeAdapterFactory.java:212)
	at sc.fiji.persist.RuntimeTypeAdapterFactory.registerSubtype(RuntimeTypeAdapterFactory.java:227)
	at sc.fiji.persist.ScijavaGsonHelper$ClassTypesAndSubTypes.lambda$getRunTimeAdapterFactory$0(ScijavaGsonHelper.java:160)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at sc.fiji.persist.ScijavaGsonHelper$ClassTypesAndSubTypes.getRunTimeAdapterFactory(ScijavaGsonHelper.java:158)
	at sc.fiji.persist.ScijavaGsonHelper.lambda$getGsonBuilder$1(ScijavaGsonHelper.java:111)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at sc.fiji.persist.ScijavaGsonHelper.getGsonBuilder(ScijavaGsonHelper.java:111)
	at sc.fiji.persist.ScijavaGsonHelper.getGson(ScijavaGsonHelper.java:63)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.setDefaultBdvSupplier(SourceAndConverterBdvDisplayService.java:129)
	at de.embl.cba.mobie.bdv.SliceViewer.createBdv(SliceViewer.java:153)
	at de.embl.cba.mobie.bdv.SliceViewer.<init>(SliceViewer.java:50)
	at de.embl.cba.mobie.view.ViewerManager.<init>(ViewerManager.java:65)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:174)
	at de.embl.cba.mobie.MoBIE.openDataset(MoBIE.java:110)
	at de.embl.cba.mobie.MoBIE.<init>(MoBIE.java:79)
	at projects.OpenRemoteYeastCLEM.main(OpenRemoteYeastCLEM.java:17)
```

Maybe because we have two such classes now with the same name?

**Comment by NicoKiaru** [comment]
> Maybe because we have two such classes now with the same name?

Maybe... Can you try with a different name

**Comment by tischi** [comment]
I removed the dependency to this repo and now it works.

**Comment by NicoKiaru** [comment]
Ok, but then you loose the displaysettings mechanism for storing and restoring colors ( I think )

**Comment by tischi** [comment]
I can add the dependency back once we remove the MoBIE classes. 

For me it would be fine to remove them now as we got things working within MoBIE: 

https://github.com/mobie/mobie-viewer-fiji/issues/338

https://github.com/mobie/mobie-viewer-fiji/blob/fbee4a82e08ed5141cfa6327d963abdc56429276/src/main/java/de/embl/cba/mobie/bdv/render/AccumulateOccludingProjectorARGB.java#L141

**Comment by NicoKiaru** [comment]
Ok doki

**Comment by NicoKiaru** [comment]
I think this issue had to be closed a long time ago. Closing now
